# Copyright (C) 2015 The Pure Nexus Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/flounder/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/htc/flounder/proprietary/lib/soundfx/libfmas.so:system/lib/soundfx/libfmas.so:htc \
    vendor/htc/flounder/proprietary/etc/fmas_eq.dat:system/etc/fmas_eq.dat:htc \
    vendor/htc/flounder/proprietary/etc/RT5506:system/etc/RT5506:htc \
    vendor/htc/flounder/proprietary/bin/cplay:system/bin/cplay:htc \
    vendor/htc/flounder/proprietary/bin/tinycap:system/bin/tinycap:htc \
    vendor/htc/flounder/proprietary/bin/tinymix:system/bin/tinymix:htc \
    vendor/htc/flounder/proprietary/bin/tinyplay:system/bin/tinyplay:htc \
    vendor/htc/flounder/proprietary/bin/xaplay:system/bin/xaplay:htc
